import arjunImage from "@/images/Dr. Arjun Singh.png";
import heroImage from "@/images/Commercial Buildings.jpg";
import logoImage from "@/images/Nanda logo.jpg";
import nitinImage from "@/images/Nitin Singh.png";
import vivekImage from "@/images/Vivek.png";
import footerPattern from "@/imports/Home/ff5318d16dd5f93f2647437a73bc8688b87582ae.png";
import type { ReactNode } from "react";

const panelClass = "bg-white rounded-[13px] shadow-[0_3px_12px_rgba(11,31,58,0.06)] p-[20px]";
const titleClass = "font-['Inter:Bold',sans-serif] font-bold text-[#244268] text-[12px] tracking-[.72px] uppercase";
const copyClass = "font-['Inter:Regular',sans-serif] leading-[20px] mt-[12px] text-[#485872] text-[12px]";
const navItems = ["Home", "About Us", "Services", "Projects", "Sustainability", "Careers", "Teams", "Contact Us"];

function Panel({ title, children, className = "" }: { title: string; children: ReactNode; className?: string }) {
  return <section className={`${panelClass} ${className}`}><h4 className={titleClass}>{title}</h4>{children}</section>;
}

function List({ items, columns = 1 }: { items: string[]; columns?: number }) {
  return <ul className={`${copyClass} grid ${columns === 2 ? "grid-cols-2 gap-x-[22px]" : "grid-cols-1"} list-disc ml-[16px]`}>
    {items.map((item) => <li className="mb-[5px]" key={item}>{item}</li>)}
  </ul>;
}

function Person({ name, role, image, values }: { name: string; role: string; image: string; values: [string, string, string, string] }) {
  return <aside className="content-stretch flex flex-col items-center shrink-0 w-[246px]">
    <img alt={name} className="bg-[#e8e8e8] h-[268px] object-cover rounded-[12px] w-[214px]" src={image} />
    <h3 className="font-['Sora:Bold',sans-serif] font-bold mt-[19px] text-[#16345e] text-[25px]">{name}</h3>
    <p className="font-['Inter:Bold',sans-serif] font-bold mt-[3px] text-[#416ca9] text-[12px] tracking-[1px] uppercase">{role}</p>
    <div className="bg-[#315d9c] grid grid-cols-2 gap-[5px] mt-[19px] p-[7px] rounded-[7px] w-[212px]">
      <div className="bg-white content-stretch flex flex-col items-center justify-center min-h-[74px] p-[7px] rounded-[3px]"><strong className="text-[#173a68] text-[19px]">{values[0]}</strong><span className="mt-[2px] text-[#40536f] text-[8px] text-center tracking-[.45px] uppercase">{values[1]}</span></div>
      <div className="bg-white content-stretch flex flex-col items-center justify-center min-h-[74px] p-[7px] rounded-[3px]"><strong className="text-[#173a68] text-[19px]">{values[2]}</strong><span className="mt-[2px] text-[#40536f] text-[8px] text-center tracking-[.45px] uppercase">{values[3]}</span></div>
    </div>
  </aside>;
}

function Arjun() {
  return <article className="bg-[#f8fafc] border border-[#9fb5d7] content-stretch flex gap-[16px] mx-auto p-[22px] rounded-[26px] w-[1210px]">
    <Person image={arjunImage} name="Dr. Arjun Singh" role="CEO" values={["40+", "Years Experience", "140+", "Airports Modernized"]} />
    <div className="content-stretch flex flex-col gap-[14px] w-[610px]">
      <Panel title="Professional Summary"><p className={copyClass}>Dr. Arjun Singh is a distinguished aviation leader with over four decades of experience in airport planning, CNS/ATM systems, airport modernization, and aviation consultancy. He has successfully led large-scale infrastructure projects, including GAGAN and GBAS implementation, while steering strategic solutions that have significantly contributed to the modernization of India&apos;s aviation sector.</p></Panel>
      <div className="content-stretch flex gap-[14px]"><Panel className="w-1/2" title="Major Achievements"><p className={copyClass}>Led GAGAN implementation in India.<br /><br />Planned GBAS deployment for Delhi &amp; Mumbai airports.<br /><br />Modernized CNS facilities across 140+ airports.<br /><br />Directed nationwide airport modernization initiatives.<br /><br />Conducted GBAS &amp; GBAS feasibility studies.<br /><br />Advised AAI on CNS maintenance strategies.<br /><br />Successfully installed, tested &amp; commissioned CNS facilities nationwide.</p></Panel><Panel className="w-1/2" title="Professional Roles"><p className={copyClass}>Managing Director, Sakshi Aviation Consultancy Services<br /><br />Program Director, U.S.-India Aviation Cooperation Program<br /><br />Joint General Manager (Communication), AAI<br /><br />Deputy General Manager (Communication), AAI<br /><br />Group &apos;A&apos; Officer, DGCA<br /><br />Lecturer, Government Polytechnic College, Lucknow</p></Panel></div>
      <Panel title="Key Expertise"><List columns={2} items={["Air Navigation Systems", "Airport Planning & Development", "Project Monitoring", "CNS/ATM Systems", "Testing & Commissioning", "Airport Modernization", "Strategic Planning", "GAGAN Implementation", "Regulatory Compliance", "GBAS Deployment", "Technical Consultancy", "Airport Modernization"]} /></Panel>
    </div>
    <div className="content-stretch flex flex-col gap-[14px] w-[292px]"><Panel title="Career Highlights"><p className={copyClass}><b>1983</b><br />Joined DGCA as Group &apos;A&apos; Officer<br />Directorate General of Civil Aviation (DGCA)<br /><br /><b>AAI</b><br />Deputy General Manager (Communication)<br />Radio Communication Development Unit<br /><br /><b>AAI</b><br />Joint General Manager (Communication)<br />Directorate of CNS - Planning &amp; D&amp;M<br /><br /><b>ACP</b><br />Programme Director<br />U.S.-India Aviation Cooperation Program (ACP)<br />Indo-American Chamber of Commerce (AACC)<br /><br /><b>SACS</b><br />Managing Director<br />Sakshi Aviation Consultancy Services (P) Ltd.</p></Panel><Panel title="Education"><p className={copyClass}><b>Ph.D.</b><br />ELECTRONICS &amp; COMMUNICATION<br /><br /><b>M.E.</b><br />MICROWAVE &amp; RADAR ENGINEERING<br /><br /><b>MBA</b><br />FINANCE<br /><br /><b>B.E.</b><br />Electronics &amp; Communication<br /><br />Chartered Engineer (India)</p></Panel></div>
  </article>;
}

function Nitin() {
  return <article className="bg-[#f8fafc] border border-[#9fb5d7] content-stretch flex gap-[16px] mx-auto p-[22px] rounded-[26px] w-[1210px]">
    <Person image={nitinImage} name="Nitin Singh" role="Site Engineer" values={["2+", "Years Experience", "5+", "Projects Executed"]} />
    <div className="content-stretch flex flex-col gap-[14px] w-[610px]"><Panel title="Professional Summary"><p className={copyClass}>Nitin Singh is a Site Engineer at Nanda Kailash Infrastructure &amp; Developers (NKID) with experience in utility-scale solar power projects. Since joining the company in January 2024, he has been involved in the installation, testing, and commissioning of solar plants for leading clients, including Adani Green Energy Ltd. (AEGL) and Avaada Solar. He has hands-on expertise in structural installation, PV module installation, tracker alignment, and quality inspections.</p></Panel><div className="content-stretch flex gap-[14px]"><Panel className="w-1/2" title="Major Achievements"><p className={copyClass}>Successfully executed MMS Assembly, PV module installation and tracker assembly projects.<br /><br />Ensured compliance with quality standards through effective supervision and inspections.<br /><br />Responded across multiple sites and adapted to project requirements efficiently.<br /><br />Contributed to timely installation and commissioning of solar plants.</p></Panel><Panel className="w-1/2" title="Key Expertise"><List items={["Solar Power Plant Installation", "PV Module Installation", "MMS Assembly", "Site Execution", "Testing & Commissioning", "Preparation for Inspection (RFI)"]} /></Panel></div></div>
    <div className="content-stretch flex flex-col gap-[14px] w-[292px]"><Panel title="Work Experience"><p className={copyClass}><b>Jan 15, 2024 - Jan 2026</b><br />Site Engineer<br />Adani Green Energy Ltd. (AEGL), Khavda, Gujarat<br /><br /><b>Jan 2026</b><br />Site Engineer<br />Avaada Solar Plant Bikaner, Rajasthan<br /><br /><b>Mar 2026 - Present</b><br />Site Engineer<br />Bhadla, Rajasthan</p></Panel><Panel title="Education"><p className={copyClass}><b>Bachelor of Engineering</b><br />(B.E.)<br />Electronics And Communication Engineering<br /><br />Completed in the year 2023</p></Panel></div>
  </article>;
}

function Vivek() {
  return <article className="bg-[#f8fafc] border border-[#9fb5d7] content-stretch flex gap-[16px] mx-auto p-[22px] rounded-[26px] w-[1210px]">
    <Person image={vivekImage} name="Vivek" role="Project Director" values={["15+", "Years Experience", "6+", "Projects Completed"]} />
    <div className="content-stretch flex flex-col gap-[14px] w-[902px]"><div className="content-stretch flex gap-[14px]"><Panel className="w-[610px]" title="Professional Summary"><p className={copyClass}>Vivek is a dynamic Project Director with 15+ years of experience across infrastructure, finance, manufacturing, and international trade. He specializes in EPC and turnkey project execution, financial planning, procurement, and project delivery. Having worked with prestigious organizations such as ICVL, Adani, Avaada, and Airports Authority of India (AAI), he is known for driving projects from planning to successful completion through strategic leadership and operational excellence.</p></Panel><Panel className="flex-1" title="Core Competencies"><List items={["Project Leadership", "Infrastructure Development", "Financial Management", "Procurement & Supply Chain", "Contract Management", "Government Coordination", "Risk Management", "Team Leadership"]} /></Panel></div><Panel title="Major Projects / Contributions"><List columns={2} items={["EPC & Turnkey Infrastructure Projects", "Government Infrastructure Projects", "Import Procurement & Logistics Management", "Financial & Project Coordination", "Site Project Coordination", "Infrastructure projects for ICVL, Adani, Avaada, and AAI"]} /></Panel><div className="content-stretch flex gap-[14px]"><Panel className="w-1/3" title="Key Expertise"><List items={["Infrastructure & EPC Project Management", "Financial Planning & Budget Control", "Manufacturing Operations", "Import & Export Operations", "Supply Chain Management", "Government Liaison & Tendering", "Contract Negotiation", "Vendor Management", "Project Execution", "Strategic Planning"]} /></Panel><Panel className="w-1/3" title="Industries Served"><List items={["Infrastructure Development", "EPC Projects", "Manufacturing", "Finance", "Import & Export", "Oil & Gas", "Aviation Infrastructure", "Energy Sector", "Government Projects"]} /></Panel><Panel className="w-1/3" title="Career Highlights"><p className={copyClass}>15+ years of cross-industry experience.<br /><br />Currently serves as Project Director at Nanda Kailash Infrastructure &amp; Developers Pvt. Ltd.<br /><br />Began career in finance and costing with expertise in budgeting and cost control.<br /><br />Led EPC and turnkey infrastructure projects.<br /><br />Successfully managed projects for ICVL, Adani, Avaada, and AAI.<br /><br />Extensive experience in procurement, logistics, and project coordination.</p></Panel></div></div>
  </article>;
}

function FooterColumn({ title, children }: { title: string; children: ReactNode }) {
  return <div className="relative w-[250px]"><h3 className="border-b border-black/25 font-['Sora:Bold',sans-serif] font-bold pb-[15px] text-[19px] text-black">{title}</h3>{children}</div>;
}

function HomeStyleFooter() {
  const footerLink = "cursor-pointer font-['Inter:Regular',sans-serif] text-[16px] text-black";
  return <footer className="border border-black bg-white h-[486px] overflow-hidden relative rounded-[5px] w-[1440px]" data-name="Footer">
    <img alt="" className="absolute inset-0 object-cover opacity-70 pointer-events-none size-full" src={footerPattern} />
    <div className="content-stretch flex h-[417px] items-start justify-between px-[64px] pt-[80px] relative">
      <div className="w-[310px]"><img alt="Nanda Kailash" className="h-[60px] object-contain w-[92px]" src={logoImage} /><p className="font-['Inter:Regular',sans-serif] leading-[27px] mt-[22px] text-[16px] text-black">Building India&apos;s Infrastructure Future<br />Through Quality Engineering,<br />Sustainable Practices, And<br />Innovative Solutions Across<br />Construction, Roads, Solar, And<br />More.</p><div className="content-stretch flex gap-[12px] mt-[17px]"><span className="bg-[#d1d1d1] border border-black/25 flex h-[30px] items-center justify-center rounded-[7px] text-[15px] w-[30px]">𝕏</span><span className="bg-[#d1d1d1] border border-black/25 flex h-[30px] items-center justify-center rounded-[7px] text-[15px] w-[30px]">𝕏</span><span className="bg-[#d1d1d1] border border-black/25 flex h-[30px] items-center justify-center rounded-[7px] text-[15px] w-[30px]">◎</span></div></div>
      <FooterColumn title="Quick Links"><div className="content-stretch flex flex-col gap-[14px] mt-[24px]"><p className={footerLink}>Home</p><p className={footerLink}>About Us</p><p className={footerLink}>Services</p><p className={footerLink}>Projects</p><p className={footerLink}>Careers</p><p className={footerLink}>Contact</p></div></FooterColumn>
      <FooterColumn title="Services"><div className="content-stretch flex flex-col gap-[14px] mt-[24px]"><p className={footerLink}>Infrastructure Development</p><p className={footerLink}>Building Construction</p><p className={footerLink}>Solar Projects</p><p className={footerLink}>Land Surveying</p><p className={footerLink}>Electrical Infrastructure</p><p className={footerLink}>Maintenance Services</p></div></FooterColumn>
      <FooterColumn title="Contact"><div className="content-stretch flex flex-col gap-[24px] mt-[24px]"><div className="content-stretch flex gap-[12px]"><span className="text-[#355d9b] text-[22px]">✉</span><p className="font-['Inter:Regular',sans-serif] leading-[21px] text-[14px] text-black"><b className="text-[16px]">EMAIL</b><br />info@nanda-kailash.in</p></div><div className="content-stretch flex gap-[12px]"><span className="text-[#355d9b] text-[22px]">♧</span><p className="font-['Inter:Regular',sans-serif] leading-[21px] text-[14px] text-black"><b className="text-[16px]">PHONE</b><br />+91 9717154147 (Mobile)</p></div><div className="content-stretch flex gap-[12px]"><span className="text-[#355d9b] text-[22px]">♙</span><p className="font-['Inter:Regular',sans-serif] leading-[21px] text-[14px] text-black"><b className="text-[16px]">ADDRESS</b><br />537, DLF Prime Towers, F-79 &amp; 80,<br />Okhla Industrial Area Phase - 1,<br />New Delhi - 110020. INDIA.</p></div></div></FooterColumn>
    </div>
    <div className="absolute bg-[#0b1f3a] bottom-0 content-stretch flex h-[68px] items-center justify-between px-[64px] text-[13px] text-white w-full"><p>© 2026 Nanda Kailash Infrastructure &amp; Developers. All rights reserved.</p><p>Infrastructure Company in India | Construction | Solar | Engineering</p></div>
  </footer>;
}

export default function Teams() {
  return <div className="bg-[#f5f8fc] font-['Inter:Regular',sans-serif] relative w-[1440px]" data-name="TEAMS">
    <nav className="bg-white content-stretch flex fixed h-[84px] items-center justify-between left-0 px-[120px] shadow-[0_2px_8px_rgba(0,0,0,0.12)] top-0 w-[1440px] z-50" data-name="NAV BAR"><img alt="Nanda Kailash" className="h-[54px] object-contain w-[86px]" src={logoImage} /><div className="content-stretch flex items-center gap-[6px]">{navItems.map((label) => <button className="bg-transparent border-0 cursor-pointer font-['Inter:Medium',sans-serif] font-medium px-[10px] py-[10px] text-[#404040] text-[16px] whitespace-nowrap" data-navigation={label} key={label} type="button">{label}</button>)}</div><button className="bg-[#fafafa] border border-[#ffce1b] cursor-pointer px-[14px] py-[11px] rounded-[4px] text-[#404040] text-[14px]" data-navigation="Get Consultation" type="button">Get Consultation</button></nav>
    <header className="h-[560px] overflow-hidden relative"><img alt="Construction project" className="absolute inset-0 object-cover size-full" src={heroImage} /><div className="absolute bg-gradient-to-r from-[#0b1f3a] inset-0 to-[rgba(11,31,58,0.15)]" /><div className="absolute left-[120px] top-[202px] w-[670px]"><span className="bg-[#365f9d] font-bold px-[12px] py-[6px] rounded-[4px] text-[12px] text-white tracking-[1px] uppercase">Team</span><h1 className="font-['Sora:Regular',sans-serif] font-bold leading-[1.1] mt-[18px] text-[58px] text-white">Meet Our Leadership<br />Team</h1><p className="leading-[26px] mt-[22px] text-[17px] text-white/80">Meet the experienced professionals driving innovation in infrastructure, engineering, consultancy and project execution.</p><button className="border border-white cursor-pointer mt-[24px] px-[28px] py-[13px] rounded-[4px] text-[15px] text-white" data-navigation="Contact Us" type="button">Contact Us</button></div></header>
    <section className="content-stretch flex gap-[90px] items-center mx-auto py-[82px] w-[1210px]"><div className="w-[580px]"><span className="bg-[#dce9f8] font-bold px-[12px] py-[6px] rounded-[4px] text-[#345d95] text-[11px] tracking-[1px] uppercase">Meet Our Team</span><h2 className="font-['Sora:Regular',sans-serif] font-bold leading-[1.18] mt-[20px] text-[#1f2f47] text-[39px]">The People Behind Every Successful Project</h2><p className="leading-[25px] mt-[22px] text-[#65738a] text-[15px]">At Nanda Kailash Infrastructure &amp; Developers, Our Strength Lies In Our People. Our Team Of Experts Brings Decades Of Experience In Infrastructure Development And Project Management To Deliver World-Class Solutions.</p></div><div className="content-stretch flex flex-col gap-[16px] w-[470px]"><div className="bg-[#ffce1b] content-stretch flex flex-col h-[120px] items-center justify-center rounded-[9px]"><strong className="text-[#28518e] text-[42px]">30+</strong><span className="font-bold text-[#28518e] text-[11px] tracking-[.5px] uppercase">Years of Experience</span></div><div className="bg-[#3966a5] content-stretch flex flex-col h-[120px] items-center justify-center rounded-[9px]"><strong className="text-[#ffce1b] text-[42px]">200+</strong><span className="font-bold text-white text-[11px] tracking-[.5px] uppercase">Projects Delivered</span></div></div></section>
    <main className="content-stretch flex flex-col gap-[38px] pb-[85px]"><Arjun /><Nitin /><Vivek /></main>
    <HomeStyleFooter />
  </div>;
}
